version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run all tests
          command: yarn test-ci
  deploy:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build and deploy
          command: yarn deploy-storybook --ci --host-token-env-variable=GITHUB_TOKEN


workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
              - master
